name: create repo

on: workflow_dispatch 

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: create repo for org     
        run: |
          
          const octokit = new Octokit({
            auth: 'YOUR-TOKEN'
          })
          
          await octokit.request('POST /orgs/{mt4621-org}/repos', {
            org: 'mt4621-org',
            name: 'Hello-World',
            description: 'This is your first repository',
            homepage: 'https://github.com',
            'private': false,
            has_issues: true,
            has_projects: true,
            has_wiki: true,
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }
          })
      
