name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
            - name: publish
              run: |
                node --version
                npm publish --access public
              working-directory: my-package
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GHE_PAT}}
